/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface DecentralBank extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): DecentralBank;
  clone(): DecentralBank;
  methods: {
    hasStaked(arg0: string): NonPayableTransactionObject<boolean>;

    isStaked(arg0: string): NonPayableTransactionObject<boolean>;

    name(): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    rwd(): NonPayableTransactionObject<string>;

    stakers(arg0: number | string | BN): NonPayableTransactionObject<string>;

    stakingBalance(arg0: string): NonPayableTransactionObject<string>;

    tether(): NonPayableTransactionObject<string>;

    depositTokens(
      _amount: number | string | BN
    ): NonPayableTransactionObject<void>;

    issueTokens(): NonPayableTransactionObject<void>;

    unstakeTokens(): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
